name: x86latency-test
version: git
version-script: |
    echo $(git describe --tags)
summary: Intel x86 kernel timer latency test
description: x86latency test performs cyclic latency measurements on the high resolution nanosleep system call.
type: app
grade: stable

confinement: strict

architectures:
    - amd64
    - i386

parts:
    x86latency-test:
        plugin: make
        source: .
        build-packages:
            - gcc
            - make
apps:
    x86latency-test:
        command: usr/bin/x86latency-test

